execute 'yum update -y'

package 'git'
package 'tree'
package 'vim' 
package 'ksh'
package 'wget'
package 'libXp'
package 'gcc'
package 'make'
package 'setarch-1.6'
package 'libaio'
package 'glibc-devel'